Tickets/dm 38195
lsst-ts/ts_externalscripts pull request #92
Opened 2023-03-06 17:52 UTC by gmegh

2023-03-06 18:18 UTC, tribeiro requested changes
Hear some initial comments. I think the most critical thing now is putting back the `additional_configuration` from your previous implementation and having the additional configurations in `LatissIntraExtraFocalData` instead of `LatissBaseAlign`.

2023-03-06 18:18 UTC, tribeiro commented on python/lsst/ts/externalscripts/auxtel/latiss_base_align.py
> +            "m2": 0,
This is a float, so probably better to keep it as `0.0`

2023-03-06 18:18 UTC, tribeiro commented on python/lsst/ts/externalscripts/auxtel/latiss_base_align.py
> +                anyOf:
I think you need something like this for all the new parameters instead:

```
type: number
default: 0.0
```

2023-03-06 18:18 UTC, tribeiro commented on python/lsst/ts/externalscripts/auxtel/latiss_base_align.py
> +                anyOf:
This one would be something like:

```
type: number
default: 0.0
maximum: 0.0
```

2023-03-06 18:18 UTC, tribeiro commented on python/lsst/ts/externalscripts/auxtel/latiss_base_align.py
> +              offset_x:
Oh! these should not be in the `LatissBaseAlign` configuration.

I think having the `additional_configuration` method and having the additional offsets in the other class was better.

2023-03-06 18:39 UTC, tribeiro reviewed
A couple more comments.

2023-03-06 18:39 UTC, tribeiro commented on python/lsst/ts/externalscripts/auxtel/latiss_base_align.py
> +        """Applies offset to the hexapod degrees of freedom.
so, `xyzuv` are hexapod but m1 is not... Maybe rephrase it:

```
Applies offsets to the AOS look-up table values.
```

We should probably rename the method as well... Maybe `offset_aos`? If you use VSCode you can easily rename method. Let me know if you need any help.

2023-03-06 18:39 UTC, tribeiro commented on python/lsst/ts/externalscripts/auxtel/latiss_base_align.py
> +            Offset to the hexapod in the z-axis mm.
Remove "to" after "Offset:

```
Offset the hexapod in the z-axis, in mm.
```

2023-03-06 18:39 UTC, tribeiro commented on python/lsst/ts/externalscripts/auxtel/latiss_intra_extra_focal_data.py
> +        """Takes Intr and Extra Focal Data.
```
Run script operation encapsulating the checkpoints to allow running standalone.
```

If you want to describe what the method does, maybe add a "Notes" session. But I am not sure this is necessary.

2023-03-06 18:39 UTC, tribeiro commented on python/lsst/ts/externalscripts/auxtel/latiss_intra_extra_focal_data.py
> +        await self.take_intra_extra()
Just to be in the safe side, maybe add a "try/except" clause here to make sure resetting the offset always happens:

```
try:
    await self.take_intra_extra()
finally:
    await self.hexapod_offset(...)
```

2023-03-06 19:53 UTC, gmegh commented
All changes made. Regarding the name of the method hexapod_offsets, could we call it dof_offsets? or you don’t like the name dof? I feel "LUT offsets" is not very clear to someone unfamiliar with LUT…

2023-03-06 21:23 UTC, tribeiro commented
You need to include:

```
from .latiss_intra_extra_focal_data import *
```

in this [__init__](https://github.com/lsst-ts/ts_externalscripts/blob/develop/python/lsst/ts/externalscripts/auxtel/__init__.py) file.

2023-03-06 23:21 UTC, tribeiro commented on python/lsst/ts/externalscripts/auxtel/latiss_intra_extra_focal_data.py
> +              offset_y:
Can you make sure the indentation on all these entries match?

2023-03-10 04:49 UTC, tribeiro approved these changes
Alright! Looks good! thanks for all the updates and hard work! I left a few final comments in the version history.. Sorry I didn't caught them earlier..

2023-03-10 04:49 UTC, tribeiro commented on doc/version_history.rst
> +v0.23.5
I think this probably deserves a minor release! Can you make this v0.24.0, please?

2023-03-10 04:49 UTC, tribeiro commented on doc/version_history.rst
> +* In ``latiss_base_algin.py``:
typo: 
latiss_base_algin.py -> latiss_base_align.py

2023-03-10 15:25 UTC, merged